### ISSUE TITLE
Make operator++ and operator-- constexpr

### ISSUE THREAD

**Issue by Eelis** [boostorg/safe_numerics#101]
```
#include <boost/safe_numerics/safe_integer.hpp>

constexpr boost::safe_numerics::safe<unsigned int> f()
{ 
    boost::safe_numerics::safe<unsigned int> x = 3;
    ++x; // error: call to non-constexpr operator++
    return x;
}
```

**Comment by pratik-a** [comment]
#include <boost/safe_numerics/safe_integer.hpp>

constexpr boost::safe_numerics::safe<unsigned int> f()
{ 
    boost::safe_numerics::safe<unsigned int> x = 3;
   x++; // error: call to non-constexpr operator++
    return x;
}[

**Comment by robertramey** [comment]
fixed this in develop branch
