### ISSUE TITLE
Cannot overload operator>> for safe_numerics::safe

### ISSUE THREAD

**Issue by Eelis** [boostorg/safe_numerics#105]
```
#include <boost/safe_numerics/safe_integer.hpp>
struct X {};
using I = boost::safe_numerics::safe<int64_t>;
void operator>>(X, I);
void f(X x, I i) { x >> i; } // causes error deep inside SafeNumerics headers
```
https://godbolt.org/z/eozM1PqW8

**Comment by Eelis** [comment]
I think the cause is that there's a bad catchall operator>> for `safe_base` that only disables itself if the lhs is derived from std::ios_base:
https://github.com/boostorg/safe_numerics/blob/e15c54c3e2d69e644d164ac51551f48e69a65eff/include/boost/safe_numerics/safe_base_operations.hpp#L1394-L1400

**Comment by robertramey** [comment]
Your correct.  I'm working on fixing it in a definitive way as we "speak".

**Comment by robertramey** [comment]
This should be fixed by now on the develop branch. Also added a test for it so it doesn't come back.  We'll leave this message until a 2nd person has confirmed it.

**Comment by robertramey** [comment]
closed/fixed

**Comment by Eelis** [comment]
Sweet, thanks!!
