### ISSUE TITLE
Document supported boost version

### ISSUE THREAD

**Issue by david-grs** [boostorg/safe_numerics#57]
Hey Robert,

Thanks for your library - I was trying to use it with g++ 7.3.0 and it took me a while to realize I missed this fix from boost.logic: https://github.com/boostorg/logic/pull/5/files

I think it would be great to document (in the README?) that this fix is needed - at least for some versions of gcc. 

Thanks!

Cheers
David

**Comment by robertramey** [comment]
the official version is being released for the first time - today?  It should work with versions of g++ > 5 without issues.  But since it's the first time, by definition - we'll have surprises
