### ISSUE TITLE
Please add links to documentation in the README.md

### ISSUE THREAD

**Issue by HDembinski** [boostorg/safe_numerics#61]
To find the documentation, I currently have to go to the Boost Incubator. Please add a link to it in the README.md. Right now, there is only a link to a talk. Having some motivating examples in the README.md would also be great.

**Comment by robertramey** [comment]
done

**Comment by HDembinski** [comment]
I don't see a link here:
https://github.com/boostorg/safe_numerics

**Comment by robertramey** [comment]
I haven't uploaded it yet.  I'm in the midst of adding a raft of new tests - testing constexpr for checked_result.  I'm a little wary of uploading small changes as the trigger a whole CI cycle while the state is still in flux.  This often generates a raft of "failures" which confuses all the issues.  Have patience.
