### ISSUE TITLE
Link to documentation in "Wiki" does not work

### ISSUE THREAD

**Issue by HDembinski** [boostorg/safe_numerics#62]
This link from the Wiki
https://github.com/boostorg/safe_numerics/wiki
does not work on my machine:
http://htmlpreview.github.com/?https://rawgit.com/boostorg/safe_numerics/master/doc/html/index.html

**Comment by robertramey** [comment]
hmm - I'd like to.  But if I remember correctly, there's a problem related to php/wordpress etc which makes this a lot harder than one would think.  Sorry about this but sticking my fingers into the incubator website is agony. the php/wordpress etc is unfriendly once the web site passes certain complexity.  On the upside - once one get's it working, it seems to work more or less forever.  Actually, I've already forgotten all the php/wordpress I had to learn so I don't know if in fact i can even fix it should that become necessary.

**Comment by HDembinski** [comment]
You closed this, but the link http://htmlpreview.github.com/?https://rawgit.com/boostorg/safe_numerics/master/doc/html/index.html still does not work.

**Comment by HDembinski** [comment]
And here is the link to your entry in blincubator
http://blincubator.com/bi_library/safe-numerics/?gform_post_id=426
copied from my browser address line.

**Comment by robertramey** [comment]
> You closed this, but the link http://htmlpreview.github.com/?https://rawgit.com/boostorg/safe_numerics/master/doc/html/index.html still does not work.

OK - Edited wiki page - everything looks good now - at least on my browser!

**Comment by HDembinski** [comment]
👍
