### ISSUE TITLE
Use boost.mp11 instead of boost.mpl

### ISSUE THREAD

**Issue by HDembinski** [boostorg/safe_numerics#63]
Since the library is C++14, it should use boost.mp11 rather than boost.mpl. boost.mp11 is faster and allows one to write cleaner code that's easier to maintain.

**Comment by HDembinski** [comment]
Nevermind, my comment was based on reading the docs. Then I looked into the source, seems like safe_numerics does not use boost.mpl directly. I suppose you listed it as a requirement because the boost libraries you depend on depend themselves on the MPL.

**Comment by robertramey** [comment]
I've recently removed the last dependence on MPL and also on Boost Preprocessor.  In it's place I'm using mp11.  I will upload changes soon.
