### ISSUE TITLE
Multiple definitions while linking

### ISSUE THREAD

**Issue by harrywong** [boostorg/safe_numerics#66]
The `make_error_code` function in `exception.hpp` is not made `inline`. So when include `safe_numerics` in multiple source files, it will turned into link error with duplicate symbols.

**Comment by robertramey** [comment]
I investigate this - see https://akrzemi1.wordpress.com/2014/07/14/inline-functions/ and I'm still not sure why this comes up.  But in any case, the function is unused from within the library and not documented as part of the API so I've fixed this by commenting out the unused function.

**Comment by harrywong** [comment]
Thanks, currently I used this workaround: add include one duplicate `exception.hpp` before include `safe_numerics` library. And I make those two functions (`make_error_code` and `make_error_condition`) as inline functions.

BTW. I tried to remove these two functions, it will turn into compile errors.

**Comment by wwqq46954** [comment]
Placing this before including boost headers worked for me:

```
// prevent multiple definitions of make_error_code
namespace boost::safe_numerics {
	enum class safe_numerics_error : std::uint8_t;
	inline std::error_code make_error_code(const ::boost::safe_numerics::safe_numerics_error& );
}
```
