### ISSUE TITLE
safe_range don't throw exceptions in VisualStudio17

### ISSUE THREAD

**Issue by Loggi-pro** [boostorg/safe_numerics#69]
Using safe_signed_range and safe_signed_range in Visual Studio 17, i noticed that they dont throw any exception, when value going out of interval. 
For example:
`safe_unsigned_range<0, 36> a =37;`
compile and don't throw any exception with default exception policy.
I tested **example5** in library, it also doesn't work.

**Comment by robertramey** [comment]
Hmmm - do you have another compiler - like the previous version of mdvc - to try?

**Comment by Ainkor** [comment]
I also have Visual Studio 2015 Update 2, but unfortunately it cannot compile this library, because it doesn't support multiple returns/switch-cases and so on in constexpr.

**Comment by robertramey** [comment]
I've had problems with different flavors of msvc compilers.  See https://www.boost.org/development/tests/develop/developer/safe_numerics.html
One thing that seems to help is building for 64 bits with the 64 bit compiler.  Also explicitly setting std=C++14 I believe has solved some problems.  (You'll have to tech the exact syntax of the C++14 option.)  Keep me informed if you figure this out!

**Comment by robertramey** [comment]
I have investigated this example (and example 84) and discovered a bug which has not been fixed.  I also added to the test suite so this issue should not return.  Thanks for finding this.  As I write this, it is still in develop branch but will migrate to master after I get some test cycles in.
Robert Ramey
