### ISSUE TITLE
bug in documentation

### ISSUE THREAD

**Issue by GregKon** [boostorg/safe_numerics#74]
Dear

I think there is subtle bug in documentation (implementation works OK):
https://www.boost.org/doc/libs/develop/libs/safe_numerics/doc/html/eliminate_runtime_penalty/1.html

code:

> int x, y;
int z = x + y               // could overflow
// so replace with the following:
int x, y;
long z = (long)x + (long)y; // can never overflow

seems is incorrect, because long and int may be both 32bits and indeed, on my machine (x86_64 gcc) and ARM 32bit what I use: long and int types are 32 bits. 
See reference:
https://en.cppreference.com/w/cpp/language/types
int is at least 32, and long is at least 32.
I think if you change on "short int" than it will be correct on any machine.

Best Regards
/Grzegorz

**Comment by GregKon** [comment]
small correction to my proposition: all types are defined  "at least .." so there is no always correct solution if used fundamental types, but my be if used fixed width types like int16_t.

**Comment by robertramey** [comment]
good catch.  I'm made the modification on my own machine.  eventually it will percolate to the master.
