### ISSUE TITLE
Support no-exception environments.

### ISSUE THREAD

**Issue by liarokapisv** [boostorg/safe_numerics#75]
The library currently cannot be used in projects where exceptions are disabled. This is due to the `exception_policies.hpp` header defining the `throw_exception` policy that makes use of the throw statement which is disallowed (forced by the compiler) in a no-exception setting. This is currently blocking us from using `safe_numerics` in our project. We want to make use of the trap policy variants but due to the `throw_exception` policy, it is not possible to include the relevant header. 
A low-cost solution would be to either define a macro and let the user override the behaviour or even separate the policies into different headers.

**Comment by johnmcfarlane** [comment]
FYI cnl:: overflow_integer supports trap behavior by default and can be
built in projects with EH disabled. https://github.com/johnmcfarlane/cnl

**Comment by robertramey** [comment]
I've pushed some changes to the develop branch which I think will address this issue.  Please try using this and let me know how it works.

**Comment by liarokapisv** [comment]
Thanks for responding this quickly to the issue! The changes seem fine in a first inspection,  I will try to test a few more configurations just for completeness sake but the changes are minimal, I don't think there will be any issues.
