### ISSUE TITLE
compiling issue 1

### ISSUE THREAD

**Issue by GregKon** [boostorg/safe_numerics#79]
Dear Robert

I have compiling issue on my compiler:

`    const union {
        R m_r;
        char const * m_msg;
    }`
in checked_results.hpp

In general const before union make warning: "type qualifiers are meaningless in this declaration" but later on compiling error. Remove const work fine.
From my knowledge it not make sense, declaration with "const" without instantiation.

**Comment by robertramey** [comment]
I agree with IAR in this case.  I'm removing the "const"

**Comment by GregKon** [comment]
Dear Robert

I have just merge from master, this patch is still not there.
It does not break anything, tested on GCC and MSVC.
