### ISSUE TITLE
Docs for safe<> do not document its semantics

### ISSUE THREAD

**Issue by akrzemi1** [boostorg/safe_numerics#92]
The docs for class template `safe<T>` at https://www.boost.org/doc/libs/1_74_0/libs/safe_numerics/doc/html/safe.html do not describe semantics of the operations, but instead refer to the description of concept `Integer`. Concept `Integer`, as any other concept, describes the operations that it requires, but it does not (because it cannot) describe what these operations do.

There is no way for me to figure out from the docs what the operations on `safe<T>` *do*. In particular, I would like to see which operations from the interface of `safe<T, PP, EP>` call which functions from `EP`:
* Which operations on `safe<T, PP, EP>` can call `EP::on_undefined_behavior()`?
* Can unary minus ever call any operation of `EP`? If so, under what conditions?

These questions about semantics cannot be answered by only referring to a concept. A concept can only say what operations (are required to) exist, but not what they do.

**Comment by robertramey** [comment]
closing this - feel free to re-open if necessary.
